-- 코드를 입력하세요
SELECT YEAR(O.SALES_DATE), MONTH(O.SALES_DATE), U.GENDER, COUNT(DISTINCT U.USER_ID)
FROM ONLINE_SALE O
JOIN USER_INFO U ON O.USER_ID = U.USER_ID
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
HAVING GENDER IS NOT NULL
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER;



# ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER