-- 코드를 입력하세요

SELECT GB.TITLE, GB.BOARD_ID, GR.REPLY_ID, GR.WRITER_ID, GR.CONTENTS, DATE_FORMAT(GR.CREATED_DATE,"%Y-%m-%d") AS CREATED_DATE
FROM USED_GOODS_BOARD GB JOIN USED_GOODS_REPLY GR USING (BOARD_ID)
WHERE GB.CREATED_DATE>="2022-10-01" AND GB.CREATED_DATE<"2022-11-01"
#WHERE TO_CHAR(GB.CREATED_DATE,"YYYYMM") ="202210"
ORDER BY GR.CREATED_DATE, GB.TITLE;